### ISSUE TITLE
Ignore `.clj-kondo/.cache`

### ISSUE THREAD

**Issue by IGJoshua** [seancorfield/deps-new#11]
The default `.gitignore` file already ignores some tool-specific files, like `clojure-lsp`'s `.lsp/sqlite.db`, but `.clj-kondo/.cache` is currently not in the default ignore list. I suggest that it be added.

**Comment by SevereOverfl0w** [comment]
https://github.com/juxt/edge/blob/master/.gitignore might be worth borrowing from.
