### ISSUE TITLE
incorporating clj-py-R template here

### ISSUE THREAD

**Issue by behrica** [seancorfield/deps-new#18]
Could it be interesting to incorporate https://github.com/behrica/clj-py-r-template here ?

my template creates a "new clojure template" + a few extra files:
- Dockerfile
- a few bash scripts to ease work with docker

- add ads as well "some" libraries for using other languages form Clojure

**Comment by behrica** [comment]
I read a bit on the template chapter and  probably it could  be achieved with me writing a template.
I will try this first

**Comment by behrica** [comment]
The template docu seems to assume that a "template" is part of the code base of a certain clojure library.
Is this correct ?

For my template above we do not have a clear "owning" library.
It brings together various libraries.

What would you advise where the "template" should go ?

**Comment by seancorfield** [comment]
I'm sorry but I don't understand what you're asking.

`deps-new` doesn't care where templates are -- it only ever looks on the classpath for directories so it's entirely up to you how you do that: the Clojure CLI lets you specify local and git-based dependencies in several ways.
