### ISSUE TITLE
Project not published to maven repositories

### ISSUE THREAD

**Issue by markokocic** [seancorfield/deps-new#24]
Right now the project is not published to maven repositories.

The only way to define dependency on deps-new is using :git/tags and :git/sha

Please consider adding to maven so that dependency can be defined using :mvn/version

**Comment by seancorfield** [comment]
Per the README:

> Note: because `deps-new` is based on `tools.build` and uses its file copying functions, the template must ultimately live on the filesystem, so `:local/root` and git-based coordinates are supported, but Maven/Clojars coordinates are not.

Which is why publishing `deps-new` to Clojars is not useful.
