### ISSUE TITLE
Failed to install, Unreadable arg: "{:git/tag"

### ISSUE THREAD

**Issue by ronniedroid** [seancorfield/deps-new#30]
I get the above error when trying to install the tool with.

`clojure -Ttools install io.github.seancorfield/deps-new '{:git/tag "v0.4.9"}' :as new`

- Fedora Linux 36 (Inside a podman container with the same os as the host)
- Both Fish and Bash shell tried.
- Clojure CLI version 1.11.1.1105

**Comment by seancorfield** [comment]
That works for me on `bash` on Ubuntu with Clojure CLI 1.11.1113 but the error indicates a failure of quoting somehow which means it's a shell issue -- it's not getting as far as `deps-new`.

Check that the `clojure` script you're using is the real CLI script -- it should start out, something like:

```bash
#!/usr/bin/env bash

set -e

install_dir=/var/www/worldsingles/build/clojure
version=1.11.1.1113

function join { local d=$1; shift; echo -n "$1"; shift; printf "%s" "${@/#/$d}"; }

# Extract opts
...
```

Or if you used `brew` to install it:

```bash
$ cat `which clojure`
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-/home/linuxbrew/.linuxbrew/opt/openjdk/libexec}" exec "/home/linuxbrew/.linuxbrew/Cellar/clojure/1.11.1.1113/libexec/bin/clojure"  "$@"
```

(which is what I have on my machine)

This isn't a `deps-new` bug -- it's something to do with your shell setup or your `clojure` script -- so I'm going to close this out and suggest you ask for help on Slack in the #tools-deps channel.

**Comment by Harikar-NGO** [comment]
so we are both on the same shell (`bash`) and we both have `clojure cli` version 1.11.1113, and we are both running on linux, isn't it weird for you that it works for you and not for me?

**Comment by ronniedroid** [comment]
so we are both on the same shell (`bash`) and we both have `clojure cli version 1.11.1113`, and we are both running on `linux`, isn't it weird for you that it works for you and not for me?

**Comment by seancorfield** [comment]
@ronniedroid Did you double-check that the `clojure` command you are actually using really is the official Clojure CLI script, and not some wrapper, as I suggested in my response? Did you check your shell aliases for a `clojure` alias?

The error you're getting indicates that something is breaking the quoting of arguments as they are passed to the CLI. That error is coming from the Clojure CLI, not from `deps-new` -- the command isn't even getting as far as `deps-new` .

**Comment by ronniedroid** [comment]
I have installed Clojure from the official `linux-install-1.11.1.xxxx.sh` script. I have no aliases or anything. 

I agree that the error is a quoting error, but I mean why is it working for you and not for me on the same shell, same version of Clojure and all?

**Comment by seancorfield** [comment]
No idea. Go ask on Slack like I suggested.
