### ISSUE TITLE
how to build ci with aliases

### ISSUE THREAD

**Issue by glfeng318** [seancorfield/deps-new#36]
the deps.edn file:
```
{:paths ["src" "resources"]
 :deps {org.clojure/clojure {:mvn/version "1.11.1"}}
 :aliases
 {:run-m {:main-opts ["-m" "etl.core"]}
  :run-x {:ns-default etl.core
          :exec-fn greet
          :exec-args {:name "Clojure"}}
  :build {:deps {io.github.seancorfield/build-clj
                 {:git/tag "v0.6.3" :git/sha "9b8e09b"
                  ;; since we're building an app uberjar, we do not
                  ;; need deps-deploy for clojars.org deployment:
                  :deps/root "slim"}}
          :ns-default build}
  :dev {:extra-deps {org.apache.spark/spark-core_2.11 {:mvn/version "2.3.4"}
                     org.apache.spark/spark-sql_2.11 {:mvn/version "2.3.4"}
                     org.apache.spark/spark-hive_2.11 {:mvn/version "2.3.4"}}
        :main-opts ["-m" "etl.core"]}
  :test {:extra-paths ["test"]
         :extra-deps {org.clojure/test.check {:mvn/version "1.1.1"}
                      io.github.cognitect-labs/test-runner
                      {:git/tag "v0.5.1" :git/sha "dfb30dd"}}}}}

```

how can i build uber with :dev aliases
i have try `clj -T:build ci` or `clj -T:build:dev ci` but fail with `ClassNotFoundException`

**Comment by seancorfield** [comment]
The `deps-new` templates use `build-clj` as a wrapper for the tasks in `build.clj` so it provides a lot of defaults that work for most projects.

However, for your project, you need a basis that uses the `:dev` alias: see https://clojure.github.io/tools.build/clojure.tools.build.api.html#var-create-basis for how to create a basis with `:aliases [:dev]` and then your `ci` task needs to pass that basis via the `:basis` argument in the options passed to the tasks.

See https://github.com/seancorfield/build-clj/blob/main/README.md for all the options available to you.

Closing this out as it is not a `deps-new` issue.

If you need help with `tools.build` or `build-clj`, I suggest joining the Clojurians Slack and asking questions in the `#tools-build` channel there.
