### ISSUE TITLE
add sr.ht and Codeberg as SCM domains

### ISSUE THREAD

**Issue by ergodicbreak** [seancorfield/deps-new#37]
What are your thoughts on adding https://git.sr.ht/ and https://codeberg.org/ as SCM domains? Of course it's easy enough to add them manually, but since these two seem like some of the bigger open source hosting domains it could be a nice convenience to have them included.

edit: PR attached since it's a minor change, though I'm not quite sure if I have the git.sr.ht domain added correctly -- apologies as this is one of the few PRs I've ever done.

**Comment by seancorfield** [comment]
Yes, it would be good to align the SCM between `deps-new` and `tools.deps.alpha` at this point. It looks like t.d.a exposes some of the machinery in its git provider so I will update `deps-new` to leverage that and update the documentation to indicate that any SCM recognized by t.d.a will be recognized by `deps-new` (so I'm going to close your PR).

**Comment by seancorfield** [comment]
Could you try `deps-new` with `:git/sha` `"dba98b22f316018072f2490fcf801cf7c80d9b72"` and see if that correctly resolves those SCM domains from the project name? I believe I've brought things in line with t.d.a.'s support.

**Comment by ergodicbreak** [comment]
Thanks for doing that! I'm including the output for anyone curious:

```
lucretius:~/work$ clojure -Sdeps '{:deps {ht.sr.wakyct/fullstack-figwheel {:git/tag "0.1.0" :git/sha "00d9b26"}}}' 
-Tnew-git-test create :template wakyct/fullstack-figwheel :name myusername/mycoollib
data-fn returning nil
template-fn returning edn
Creating project from wakyct/fullstack-figwheel in mycoollib
lucretius:~/work$ ls -R mycoollib/
mycoollib/:
CHANGELOG.md       build.clj          doc                prod.cljs.edn      test
LICENSE            deps.edn           figwheel-main.edn  resources
README.md          dev.cljs.edn       pom.xml            src

mycoollib/doc:
intro.md

mycoollib/resources:
public

mycoollib/resources/public:
css         index.html

mycoollib/resources/public/css:
style.css

mycoollib/src:
myusername

mycoollib/src/myusername:
mycoollib

mycoollib/src/myusername/mycoollib:
backend.clj    frontend.cljs

mycoollib/test:
myusername

mycoollib/test/myusername:
mycoollib

mycoollib/test/myusername/mycoollib:
backend_test.clj    frontend_test.cljs
lucretius:~/work$ 
```

By the way, I wasn't sure the best way to try a specific sha of deps-new -- was downloading that specific version of the tool and naming it something other than 'new' like I did the way to do it?

**Comment by seancorfield** [comment]
You should be able to install any version of a tool using the regular CLI. Specify the full `:git/sha` of the commit you want and omit `:git/tag`

**Comment by ergodicbreak** [comment]
Sorry, by 'downloading' I meant installing through the CLI. I wasn't sure if there was a way to run the already installed CLI tool with an optional sha to temporarily depend on a different git tag.

**Comment by seancorfield** [comment]
This has been documented. Closing.
