### ISSUE TITLE
Consider not using .clj for extension of template source files

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/deps-new#39]
These files are not valid Clojure (and probably are not valid EDN either).

This should help avoid problems with tooling downstream, for anything that might assume it can load `.clj` files as Clojure code.

Probably ought to update the docs too, so folks building their own templates do not trip over this.

**Comment by imrekoszo** [comment]
For the sake of documentation and for anyone trying to look into the whys:

- a [related comment](https://ask.clojure.org/index.php/11434/could-namespace-refresh-sophisticated-directory-filtering?show=11882#c11882) from Alex Miller
- a [related clj-kondo issue](https://github.com/clj-kondo/clj-kondo/issues/1685)

**Comment by seancorfield** [comment]
A note about this: `deps-new` can either copy entire directories (recursively) or individual files. When copying individual files, it's easy to take any source file and copy it to a `.clj` file (or whatever) but directories are copied "as-is" (modulo internal `{{var}}` substitution).

The existing templates contain a `root` folder that is copied to the new project folder and includes `build.clj`, so that file is going to need to be pulled out separately in order to change its file extension.

**Comment by seancorfield** [comment]
Fixed in v0.5.0
