### ISSUE TITLE
Consider supporting additional document formats like AsciiDoc?

### ISSUE THREAD

**Issue by KingMob** [seancorfield/deps-new#40]
It's not a big deal, but I generally find AsciiDoc superior to Markdown, and prefer it. It would be nice if all the example docs (README, CHANGELOG, and intro) could be created in AsciiDoc. Just a thought.

**Comment by seancorfield** [comment]
I'm not sure what you're asking? You can create templates with whatever content you want to generate your own projects.

**Comment by KingMob** [comment]
Yes, but I was thinking more like a flag to one of the existing templates, so it would be widely available. AFAIK, there's no good way yet to locate other deps-new templates. (The point of open source to me is sharing; if I wanted to keep a template for myself, I wouldn't have raised an issue.)

Maybe a better way to solve the problem is to ask: can you add something to support discovery of non-default templates? A section in the README, or enable the GH wiki, so people can add their templates, perhaps?

**Comment by seancorfield** [comment]
Happy to take a PR for that but is AsciiDoc really that widely used? I've hardly ever seen it in a GH repo...

**Comment by KingMob** [comment]
I feel like I see it often enough, though Markdown is definitely more popular. Unfortunately, its name is a bit misleading: using "ASCII" makes it sound old, but it's really better-designed than Markdown.

If it's OK, I'll make a template, and submit a PR to add a section in the README for external templates (unless you'd prefer to go the Wiki page route).

**Comment by seancorfield** [comment]
Sure. A PR for the README sounds good. Thanks! Hopefully it'll encourage others to get their templates listed too.

**Comment by KingMob** [comment]
No prob. 

~~One minor thing that threw me off: the README has a section called "Create a Template", which sounds like it's used to bootstrap new templates, but iiuc, it's used to create FROM templates.~~

EDIT: never mind, it _is_ used to bootstrap templates, but since the `templates.md` file doesn't talk about the need to make it available via the classpath, the resulting directory layout was confusing. (I was expecting a template.edn and a /root)

**Comment by KingMob** [comment]
Hmmm, probably need to update the "Writing Templates" doc to talk about deployment, too. IIUC, to consume over git requires the template be in a valid Clojure/Java project (e.g., under `resources/`). It's not just downloading files to a directory from git (though that would be handy, since it's not really a clojure/java project).

**Comment by seancorfield** [comment]
@KingMob Thanks for that PR. Is this issue addressed now, or do you think more is needed?

**Comment by KingMob** [comment]
LGTM!
