### ISSUE TITLE
Consider publish to mvn also?

### ISSUE THREAD

**Issue by sg-qwt** [seancorfield/deps-new#48]
I'd like to add it to deps.edn manually with `:mvn/version`, if deps-new could be published to mvn would be nice.

**Comment by seancorfield** [comment]
Why? What problem does that solve?

`deps-new` is designed to be installed as a CLI tool but you can also use it as a git dep.

**Comment by sg-qwt** [comment]
in the old mvn world, there is `:mvn/version "RELEASE"`, but I don't find the equivalent in the new :git/tag way?

**Comment by seancorfield** [comment]
If you install it as a tool, there's a built-in way to update tools to the latest version.

Can you explain the use case where you're trying to use this as a library instead of a tool?

**Comment by sg-qwt** [comment]
check the linked deps.edn for example: https://github.com/sg-qwt/nixos/blob/050fbb94e067645610dbe8f929776820c7f2a290/config/clojure/deps.edn

In the dev profile, I can simply defined that declaratively and call it a day. No need to worry about update latest git tag and hash. But as said, if deps-new is solely designed as used of tool, that's fine by me. I personally prefer the old dep.edn way though. Not the new tool way.

The tool way is more a imperative workflow to me, ie: if i go to a new computer, I run clj -Ttools install, remove,update manually.

While deps.edn way is declarative, I declare the deps.edn once and link it to anywhere, thats all.

**Comment by seancorfield** [comment]
FWIW, I keep my user config for the Clojure CLI in git too -- https://github.com/seancorfield/dot-clojure/tree/develop/tools -- and I include the tools installations that way too, so I can leverage the idiomatic `clojure -Ttools` stuff for listing/updating etc.

`deps-new` requires templates that are git or local deps so making `deps-new` itself available as a Maven (Clojars) coordinate seems weird.
