### ISSUE TITLE
When updating dependencies in deps.edn, the method for adjusting the dependency repository

### ISSUE THREAD

**Issue by PlumpMath** [seancorfield/deps-new#50]
Hello

Is there a way to update the versions of dependencies in deps.edn using the command clojure -M:outdated, without being affected by .m2/settings.xml, and by setting up the dependency repository within deps.edn? It seems like the error is occurring because it only looks at the basic maven repository.

https://github.com/ertugrulcetin/jme-clj/issues/13#issue-1704776789

Thanks.

**Comment by seancorfield** [comment]
Your question seems to have nothing to do with this project.

**Comment by PlumpMath** [comment]
;;; Really? Update feature? Isn't it something you made? 
I just assumed you made it since you manage the clj-new features and there have been many changes in the options. Sorry about that;. 
By any chance, do you know who I should ask about this? 
Thank you.

**Comment by seancorfield** [comment]
"outdated" has nothing to do with clj-new either.

What is your `:outdated` alias defined as? There are several projects out there that check dependency versions...

**Comment by seancorfield** [comment]
Are you perhaps using this project: https://github.com/liquidz/antq ?
