### ISSUE TITLE
Some of template seems too old to use

### ISSUE THREAD

**Issue by idhowardgj94** [seancorfield/deps-new#51]
As title,

for example, some template like electron-app still use `clojure -A` in readme, which is been deprecated and not suggest by clojure official,

also, some template can't build now, 
I use electron in my Macs Monterey 12.5
when I follow the readme to start dev environment,
it show a blank electron window.

does anyone maintain the templates anywhere?

**Comment by seancorfield** [comment]
Sounds like you're talking about https://github.com/paulbutcher/electron-app ?

**Comment by idhowardgj94** [comment]
Yes, I see, so it's mantain on other repo.

**Comment by seancorfield** [comment]
Yes. Only a few simple templates are built-in to `deps-new` -- `app`, `lib`, `scratch`, `pom` -- all the rest are created and maintained by the community and I have no control over those.

You can find the community templates via https://clojars.org/search?q=clj-template and most of those should link to the GitHub repo behind the template.

**Comment by seancorfield** [comment]
Yes. Only a few simple templates are built-in to `deps-new` -- `app`, `lib`, `scratch`, `pom` -- all the rest are created and maintained by the community and I have no control over those.

In addition, most of the `clj-template` projects -- and in particular the ones you'll find on https://clojars.org -- are **not** `deps-new` templates, they are https://github.com/seancorfield/clj-new templates (but, again, those templates are maintained by the _community_ and not by me).
