### ISSUE TITLE
Running basic tests for a new app

### ISSUE THREAD

**Issue by adwelly** [seancorfield/deps-new#52]
Creating an app with the command:

$ clojure -Tnew app :name myusername/mynewapp

Seems to produce all the boilerplate and directories that are needed to get going but there's little guidance on executing the basic (failing) tests that are generated at the same time which is a problem for newcomers to the concept of test-runners. Reading around suggests that the command

$ cd mynewapp
$ clj -X:test

should be sufficient to kick things off but this produces the error message:

"No function found on command line or in :exec-fn"

What's the right way to execute the tests? Could something be added to the README?

**Comment by seancorfield** [comment]
Each generated project's README had instructions on what to do:

    $ clojure -T:build test

But I'll update the parent repo to make it clear that the generated README has all the details on running the project, running tests, and building it.

**Comment by adwelly** [comment]
Thanks. The one place I didn't think to look. Doh!
